# Generated by Django 4.0.3 on 2022-04-07 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Course title')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short description of the Course')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long description of the Course')),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=50, unique=True, verbose_name='Name of the discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Class title')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short description of the Class')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long description of the Class')),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.unit')),
            ],
            options={
                'unique_together': {('unit', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.ManyToManyField(through='course.CourseUnits', to='course.unit'),
        ),
    ]
