name: website-mitotique CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    steps:
      - name: Build
        uses: ./.github/workflows/build.yaml
  
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
  
  deployStaging:
    name: Staging Deployment
    runs-on: ubuntu-latest
    needs: [ build ]
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} || 'http://www.google.com'  # Remove the link to google once correct app is deployed
    
    steps:
    - name: Deploy infrastructure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: mitotique-dev
        template: ./bicep/website.bicep
        parameters: environment="dev"
    
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .
        
    # - name: 'Deploy to Azure Web App'
    #   uses: azure/webapps-deploy@v2
    #   id: deploy-to-webapp
    #   with:
    #     app-name: 'mitotique-dev'
    #     slot-name: 'Production'
    #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_50B72AC76B094B94B050340EAEB1AB00 }}

  deployProd:
    runs-on: ubuntu-latest
    needs: deployStaging
    run: echo "Production deployment Ran"