name: website-mitotique CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        echo "Running Tests!!"
        # python manage.py test

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: website-mitotique
        path: |
          . 
          !venv/
  
  deployStaging:
    name: Staging Deployment
    runs-on: ubuntu-latest
    needs: [ build ]
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} || 'http://www.google.com'  # Remove the link to google once correct app is deployed
    
    steps:
      - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: website-mitotique
        path: .
  
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy infrastructure
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: mitotique-dev
        template: ./website-mitotique/bicep/website.bicep
        parameters: environment="dev"
        
    # - name: 'Deploy to Azure Web App'
    #   uses: azure/webapps-deploy@v2
    #   id: deploy-to-webapp
    #   with:
    #     app-name: 'mitotique-dev'
    #     slot-name: 'Production'
    #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_50B72AC76B094B94B050340EAEB1AB00 }}

  deployProd:
    runs-on: ubuntu-latest
    needs: deployStaging
    steps:
      - name: Dummy Step
        run: echo "Production deployment Ran"