name: website-mitotique workflow template

on:
  push:
    branches:
      - "develop"

  pull_request:
    branches:
      - "master"

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy job"
